[build-system]
requires = ["setuptools>=61.0", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_file = "aigym/_version.py"

[project]
name = "aigym"
dynamic = ["version"]
authors = [{ name = "Niels Bantilan", email = "niels.bantilan@gmail.com" }]
description = "Reinforcement learning environments for fine-tuning language models for reasoning tasks."
license-files = ["LICENSE"]
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4",
    "html2text",
    "httpx",
    "gymnasium",
    "markdown",
    "markdownify",
    "numpy",
    "pydantic",
    "pygame",
    "python-dotenv",
    "rich",
    "tiktoken",
]
classifiers = [
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "License :: Other/Proprietary License",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.optional-dependencies]
flyte = [
    "flyte==2.0.0b24",
]
ollama = [
    "ollama",
]
openai = [
    "openai",
]
google-genai = [
    "google-genai",
]
trl = [
    "trl",
    "torch>=2.7.0",
    "numpy>2",
]
peft = [
    "peft>=0.17.0",
]
bitsandbytes = [
    "bitsandbytes>=0.42.0",
]
transformers = [
    "transformers",
    "torch>=2.7.0",
]
wandb = [
    "wandb",
]

[dependency-groups]
dev = [
    "pre-commit",
    "black",
    "ruff",
    "pytest",
    "twine",
]

[project.urls]
Homepage = "https://github.com/cosmicbboy/aigym"

[tool.setuptools.packages.find]
include = ["aigym*"]

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
markers = []

[tool.coverage.run]
branch = true

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "W", "F", "I"]
ignore = ["E501"]
